#! /bin/bash

# binaries output directory (objects and executables are placed there)
OUTDIR=bin
[ -d $OUTDIR ] || mkdir $OUTDIR


as --32 $1.s -o $OUTDIR/$1.o \
	&& ld -m elf_i386 $OUTDIR/$1.o -o $OUTDIR/$1 \
	&& $OUTDIR/$1


